spring:
  application:
    name: gestao-patrimonio-imobiliario
  datasource:
    url: jdbc:postgresql://localhost:5433/gestao_patrimonio_imobiliario
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 5000
            loggerLevel: basic

# Provedor externo de consulta de endereço por CEP.
integracao:
  viacep:
    url: https://viacep.com.br/ws
